---
abstract: "use HTML::TreeBuilder::LibXML for testing\nweb-sites."
author:
  - 'Shlomi Fish <shlomif@insurgentsoftware.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-LibXML
provides:
  Test::WWW::Mechanize::LibXML:
    file: lib/Test/WWW/Mechanize/LibXML.pm
    version: v0.0.1
requires:
  HTML::TreeBuilder::LibXML: 0
  Test::WWW::Mechanize: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.1
